# Generated by Django 3.2.24 on 2024-02-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=20)),
                ('Lastname', models.CharField(max_length=20)),
                ('EmailAddress', models.EmailField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='students',
            old_name='date_of_birth',
            new_name='Date_of_Birth',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='emailaddress',
            new_name='EmailAddress',
        ),
        migrations.AlterModelTable(
            name='students',
            table='Wanafunzi',
        ),
    ]
