# Generated by Django 3.2.24 on 2024-02-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelapp', '0002_auto_20240228_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=20)),
                ('Lastname', models.CharField(max_length=20)),
                ('EmailAddress', models.EmailField(max_length=30)),
                ('Phone_No', models.IntegerField()),
                ('ID_No', models.IntegerField()),
            ],
        ),
    ]
