# Generated by Django 3.2.24 on 2024-02-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelapp', '0003_parents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('CourseName', models.CharField(max_length=20)),
                ('CourseID', models.IntegerField()),
                ('Grade', models.IntegerField()),
                ('Student_ID', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('Author', models.CharField(max_length=20)),
                ('Date_Updated', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='students',
            name='id',
        ),
        migrations.AddField(
            model_name='students',
            name='Student_ID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
